steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/project-cfd0578a-68eb-49ae-82d/forecast-repo:$SHORT_SHA',
      '.'
    ]
images:
  - 'gcr.io/project-cfd0578a-68eb-49ae-82d/forecast-repo:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY